import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:5200/", { waitUntil: "networkidle" });
console.log((await p.locator(".proofs").count()) === 0 ? "PASS proof bar gone" : "FAIL proofs remain");
await p.keyboard.press("/");
await p.waitForSelector(".term-window");
await p.waitForTimeout(1500);
const t = await p.innerText(".term-scroll");
console.log(!/list commands/.test(t) ? "PASS no auto-help clutter" : "FAIL auto-help still runs");
const chips = await p.locator(".term-chip").allInnerTexts();
console.log(!chips.includes("stats") ? `PASS chips: ${chips.join(",")}` : "FAIL stats chip");
await p.fill(".term-input", "agent"); await p.keyboard.press("Enter"); await p.waitForTimeout(600);
console.log(/RAG over everything/.test(await p.innerText(".term-scroll")) ? "PASS 'agent' alias boots agent" : "FAIL alias");
await p.fill(".term-input", "exit"); await p.keyboard.press("Enter"); await p.waitForTimeout(300);
await p.locator(".term-light-close").click();
const closed = await p.waitForSelector(".term-window", { state: "detached", timeout: 3000 }).then(() => true).catch(() => false);
console.log(closed ? "PASS red light closes window" : "FAIL close button");
await b.close();
